### ISSUE TITLE
Programmatically choosing dates

### ISSUE THREAD

**Issue by ugenlik** [PeteC/DSLCalendarView#15]
How can I programmatically choose dates? or Start with initial dates are chosen? 

I tried 

```
NSDateComponents *startDateForRange = [startingDate dslCalendarView_dayWithCalendar:self.calendarView.visibleMonth.calendar];
NSDateComponents *endDateForRange = [EndDate dslCalendarView_dayWithCalendar:self.calendarView.visibleMonth.calendar];
DSLCalendarRange *newRamnge=[[DSLCalendarRange alloc] initWithStartDay:startDateForRange endDay:endDateForRange];
[self calendarView:self.calendarView didDragToDay:endDateForRange selectingRange:newRamnge];
```

 //[self calendarView:self.calendarView didSelectRange:newRamnge];

//startingDate  and EndDate are valid nsdates

**Comment by harrypotter30022003** [comment]
I need this as well...

Any help would be much appreciated

**Comment by sergiomtzlosa** [comment]
I think that setSelectedRange: method from DSLCalendarView does the magic:

```
NSDate *today = [NSDate date];
NSDate *end = [today dateByAddingTimeInterval:7 * 24 * 3600];

NSCalendar *calendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
[calendar setTimeZone:[NSTimeZone systemTimeZone]];
NSDateComponents *dateCompStart = [calendar components:NSCalendarCalendarUnit | NSYearCalendarUnit | NSMonthCalendarUnit | NSDayCalendarUnit | NSWeekdayCalendarUnit fromDate:today];
NSDateComponents *dateCompEnd = [calendar components:NSCalendarCalendarUnit | NSYearCalendarUnit | NSMonthCalendarUnit | NSDayCalendarUnit | NSWeekdayCalendarUnit fromDate:end];

DSLCalendarRange *range = [[DSLCalendarRange alloc] initWithStartDay:dateCompStart endDay:dateCompEnd];

[self.calendarView setSelectedRange:range];
```

**Comment by harrypotter30022003** [comment]
how about programmatically unselect everything?

**Comment by Airtower** [comment]
I cannot get this to work. When i use this, the calendar selects all the dates instead of just the range of 4 days i sent it. 

Heres my code:

 NSDateComponents *startComps = [gregorianCalendar components:NSCalendarUnitTimeZone | NSCalendarUnitYear | NSCalendarUnitMonth | NSCalendarUnitDay fromDate:trip.fStartDate];
    NSDateComponents *endComps = [gregorianCalendar components:NSCalendarUnitTimeZone | NSCalendarUnitYear | NSCalendarUnitMonth | NSCalendarUnitDay fromDate:trip.fEndDate];
DSLCalendarRange *range = [[DSLCalendarRange alloc] initWithStartDay:startComps endDay:endComps];

```
[_calendarView setSelectedRange:range];
```
