### ISSUE TITLE
show current date when calendar loads 

### ISSUE THREAD

**Issue by hemangshah** [PeteC/DSLCalendarView#21]
I want to show current date selected when calendar loads.

I've tried using,

```
NSDate *today = [NSDate date];
NSCalendar *gregorian = [[NSCalendar alloc]
                         initWithCalendarIdentifier:NSGregorianCalendar];
NSDateComponents *component = [gregorian components:(NSCalendarUnitDay|NSCalendarUnitMonth|NSCalendarUnitYear) fromDate:today];

[_calendarView setSelectedRange:[[DSLCalendarRange alloc] initWithStartDay:component endDay:component]];
```

But its selecting each and every day into the calendar.

Any solution?

**Comment by EvgenyKarkan** [comment]
Hi !
You may check out my pull request #19. 
I provide simple solution for set current day marked with another color.

**Comment by hemangshah** [comment]
@EvgenyKarkan, thanks man! It's helped me!

**Comment by EvgenyKarkan** [comment]
Glad to hear it. Cool :)

**Comment by rafaelalmoraes** [comment]
Hi, I need uncheck current day when touch in another day.

Thanks.
