### ISSUE TITLE
Change start day of week in calendar

### ISSUE THREAD

**Issue by hemangshah** [PeteC/DSLCalendarView#22]
Right now, we're getting days as Sun Mon Tues Wed Thu Fri Sat... Can I set day to start with Mon.. So the calendar will be displayed like, Mon Tue Wed Thu Fri Sat Sun..? Is it possible?

**Comment by EvgenyKarkan** [comment]
If I am not mistaken - the start day of week depends on user's locale. So you should not do it manually.

**Comment by hemangshah** [comment]
However, we can't set it manually? As its custom calendar, so we can do that, I think.

**Comment by EvgenyKarkan** [comment]
Maybe. 
Unfortunately I did not have much time to deal with all DSLCalendar API's. 
Very interesting to hear the repo author's response :)

**Comment by hemangshah** [comment]
yeah :)

**Comment by hemangshah** [comment]
@PeteC, have you provided this in your library? Or there's some way I can change this? Let me know, if there's an option.

**Comment by a1exb1** [comment]
please let me know if this is possible, i am in very big need of this feature
